# to make walkability a functioning package

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "walkability"
version = "0.1.0"
description = "Predicting neighborhood walkability from satellite imagery using a CNN"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "torch",
    "torchvision",
    "torchmetrics",
    "pandas",
    "Pillow",
    "geopandas",
    "requests",
    "tqdm",
    "scikit-learn",
    "ipykernel",
    "jupyter",
    "notebook",
    "pytorch_lightning",
    "matplotlib"
]

[tool.setuptools.packages.find]
include = ["walkability*"]
